### ISSUE TITLE
Typescript errors on version 4.3.0

### ISSUE THREAD

**Issue by beetlebum** [helmetjs/helmet#283]
Two new errors have appeared on the typescript definitions after upgrading to 4.3.0:

```$ tsc && ts-node-dev --respawn --watch 'src/**' --transpile-only src/index.ts
node_modules/helmet/dist/middlewares/content-security-policy/index.d.ts:21:70 - error TS1335: 'unique symbol' types are not allowed here.

21         [x: string]: Iterable<ContentSecurityPolicyDirectiveValue> | unique symbol;
                                                                        ~~~~~~~~~~~~~

node_modules/helmet/dist/middlewares/content-security-policy/index.d.ts:23:9 - error TS1332: A variable whose type is a 'unique symbol' type must be 'const'.

23     var dangerouslyDisableDefaultSrc: unique symbol;
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by EvanHahn** [comment]
Thanks for letting me know.

What version of TypeScript are you using?

**Comment by beetlebum** [comment]
`^4.1.3`

**Comment by EvanHahn** [comment]
Ah, I'm now seeing the error. I'll push up a fix soon, likely v4.3.1.

**Comment by EvanHahn** [comment]
I just opened #284 which should fix this issue. I'll let you know when I release it.

**Comment by EvanHahn** [comment]
This should be fixed in `helmet@4.3.1`. Thanks for reporting!
